#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=train_model
#SBATCH --ntasks=1
#SBATCH --time=40:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate dl4nlp_gpu

cd $HOME/AdversarialGenAIDetector
python src/train.py --epochs 10 --model RobertaLarge --with_data_augmentations --output_dir output_roberta_augmentations
